# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f6f32adfc8f1487ea2d5298ed374ddd6bf6192945eda4e975ff8e49fcabdf5c7c11d58e9a3792dbeb25e75302e595feac2f5abcf0e23d83ed2944d89291c855
  telegram:
    bot: '415804146:AAFNk6ZZERN5tSuYoYXQf-qPQx1IAcg9FDc'
    username: 'Заказ шаурмы'

test:
  secret_key_base: 61ecf3eb305bddca9b4c1563c5ba41a5282aa9005eeb19d1c28be4683096ba0ce097186681341f5bbe6eb36a8955a71c614f7a28dfcb3f328de28324ba5c7c92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
   telegram:
      bot: '415804146:AAFNk6ZZERN5tSuYoYXQf-qPQx1IAcg9FDc'
      username: 'Заказ шаурмы'
